version: '3'

services:
  generator:
    image: 192.168.1.110:5000/gen:ci-${GENERATOR_BUILD_NUMBER-14}
    ports:
      - "8080:80"
  mail:
    image: mailhog/mailhog
    ports:
      - "8081:8025"
#test
